--- #YAML:1.0
name: Acme-Brainfuck
version: 1.1.0
author:
  - Jaldhar H. Vyas <jaldhar@braincells.com>
abstract: Embed Brainfuck in your perl code
license: unrestricted
provides:
  Acme::Brainfuck:
    file: lib/Acme/Brainfuck.pm
    version: 1.1.0
generated_by: Module::Build version 0.24
